export const defaults = {
	data: {
		labels: [],
		values: [],
	},
	axisFontSize: '1rem',
	axisRoughness: 0.5,
	axisStrokeWidth: 0.5,
	bowing: 0,
	colors: [ 'coral', 'skyblue', '#66c2a5', 'tan', '#8da0cb', '#e78ac3', '#a6d854', '#ffd92f', 'tan', 'orange' ],
	colorVar: 'Tomato',
	curbZero: false,
	fillStyle: 'cross-hatch',
	fillWeight: 0.2,
	fontFamily: 0,
	highlight: 'Tomato',
	innerStrokeWidth: 1,
	interactive: false,
	labelFontSize: '2rem',
	margin: { top: 50, bottom: 70, left: 100, right: 20 },
	radius: '8',
	roughness: 1,
	simplification: 0.1,
	stroke: '#bd006d',
	strokeWidth: 2,
	title: '',
	titleFontSize: '2rem',
	tooltipFontSize: '1rem',
	xLabel: '',
	yLabel: '',
	width: 400,
	height: 300,
};

export const preview = {
	x: 0,
	y: 0,
	zoom: 0.6,
	maxZoom: 5,
	minZoom: 0.1,
};
