export const defaults = {
	data: {
		labels: [],
		values: [],
	},
	axisFontSize: '1rem',
	axisRoughness: 0.5,
	axisStrokeWidth: 0.5,
	bowing: 0,
	color: 'DeepPink',
	fillStyle: 'cross-hatch',
	fillWeight: 0.2,
	fontFamily: 0,
	highlight: 'Tomato',
	innerStrokeWidth: 1,
	interactive: false,
	labelFontSize: '1rem',
	margin: { top: 50, right: 20, bottom: 70, left: 100 },
	padding: 0.1,
	roughness: 1,
	simplification: 0.2,
	stroke: '#bd006d',
	strokeWidth: 1,
	title: '',
	titleFontSize: '1rem',
	tooltipFontSize: '0.95rem',
	xLabel: '',
	yLabel: '',
	width: 400,
	height: 300,
};

export const preview = {
	x: 0,
	y: 0,
	zoom: 0.6,
	maxZoom: 5,
	minZoom: 0.1,
};
