
export const config = {
	data: {
		labels: [],
		values: [],
	},
	color: 'DeepPink',
	title: '',
	axisRoughness: 0.5,
	circle: true,
	circleRadius: '10',
	circleRoughness: '2',
	colorVar: 'tomato',
	width: 400,
	height: 300,
	axisStrokeWidth: 0.5,
	bowing: 0,
	fillStyle: 'cross-hatch',
	fillWeight: 0.2,
	fontFamily: 0,
	highlight: 'tomato',
	innerStrokeWidth: 1,
	interactive: true,
	margin: { top: 35, bottom: 10, left: 150, right: 10 },
	padding: 0.2,
	roughness: 4,
	simplification: 0.1,
	stroke: '#bd006d',
	strokeWidth: 2,
	axisFontSize: '1rem',
	labelFontSize: '2rem',
	titleFontSize: '2rem',
	tooltipFontSize: '1rem',
	xLabel: '',
	yLabel: '',
	legend: false,
	legendPosition: 'left',
};
