export const CONFIG = {
	data: {
		labels: [],
		values: [],
	},
	color: 'DeepPink',
	title: '',
	axisRoughness: 0.5,
	circle: false,
	circleRadius: '10',
	circleRoughness: '2',
	colorVar: 'Tomato',
	width: 400,
	height: 300,
	axisStrokeWidth: 0.5,
	bowing: 0,
	fillStyle: 'cross-hatch',
	fillWeight: 0.2,
	fontFamily: 0,
	highlight: 'Tomato',
	innerStrokeWidth: 1,
	interactive: false,
	margin: { top: 35, bottom: 10, left: 150, right: 10 },
	padding: 0.2,
	roughness: 4,
	simplification: 0.1,
	stroke: '#bd006d',
	strokeWidth: 2,
	axisFontSize: '1rem',
	labelFontSize: '2rem',
	titleFontSize: '2rem',
	tooltipFontSize: '1rem',
	xLabel: '',
	yLabel: '',
	legend: false,
	legendPosition: 'left',
};

export const ATTRIBUTES = [
	'title',
	'color',
	'highlight',
	'roughness',
	'stroke',
	'strokeWidth',
	'axisStrokeWidth',
	'axisRoughness',
	'innerStrokeWidth',
	'fillStyle',
	'bowing',
	'fillWeight',
	'simplification',
	'interactive',
	'titleFontSize',
	'axisFontSize',
	'tooltipFontSize',
	'font',
	'dataFormat',
	'labels',
	'values',
	'padding',
	'xLabel',
	'yLabel',
	'labelFontSize',
	'fontFamily',
	'circle',
	'circleRadius',
	'circleRoughness',
	'colorVar',
	'curbZero',
	'legend',
	'legendPosition',
];

export const PREVIEW = {
	x: 0,
	y: 0,
	zoom: 0.6,
	maxZoom: 5,
	minZoom: 0.1
  };